### ISSUE TITLE
Swap Glyphs.py line 30 needs parenthesis

### ISSUE THREAD

**Issue by danielnisbet** [Mark2Mark/Glyphsapp-Scripts-Free#2]
Glyphs 3 throws an error requiring parenthesis:

`print listOfGlyphNames`

Changed it on my file to:

`print(listOfGlyphNames)`

And it resolves the error

**Comment by djrrb** [comment]
https://github.com/Mark2Mark/Glyphsapp-Scripts-Free/pull/3

**Comment by Mark2Mark** [comment]
Thanks a lot, you both.
